<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>gg.archipelago.rhythmdoctor</AssemblyName>
    <TargetName>RhythmDoctor.Archipelago</TargetName>
    <Product>RhythmDoctor.Archipelago</Product>
    <Version>0.0.1</Version>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> <!-- Copy over required libraries such as YamlDotNet -->
    <RootNamespace>RhythmDoctor.Archipelago</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- MSB3277: Found conflicts between different versions of "System.IO.Compression" that could not be resolved. -->
  <PropertyGroup>
    <MSBuildWarningsAsMessages>
      $(MSBuildWarningsAsMessages);MSB3277
    </MSBuildWarningsAsMessages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.*" />
    <PackageReference Include="Archipelago.MultiClient.Net.Analyzers" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="*" PrivateAssets="all" /> <!-- https://semver.org/#spec-item-4: Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. -->
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="Nitrox.Discovery.MSBuild" Version="0.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeFixes" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.7" IncludeAssets="compile" />
    <PackageReference Include="YamlDotNet" Version="16.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="FindGameAndIncludeReferences" BeforeTargets="ResolveAssemblyReferences" Condition="'$(_NitroxDiscovery_TaskAssembly)' != ''">
    <PropertyGroup>
      <GameName>Rhythm Doctor</GameName>
    </PropertyGroup>
    <DiscoverGame GameName="$(GameName)">
      <Output TaskParameter="GamePath" PropertyName="GameDir" />
    </DiscoverGame>
    <PropertyGroup>
      <GameDir>$(GameDir)\Rhythm Doctor_Data\Managed\</GameDir>
      <GameDir Condition="'$(GameDir)' == '\Rhythm Doctor_Data\Managed\'">libs\</GameDir>
    </PropertyGroup>
    
    <Message Importance="high" Text="Using libraries at '$(GameDir)'" />

    <ItemGroup>
      <Reference Include="Assembly-CSharp" Publicize="true">
        <HintPath>$(GameDir)\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>$(GameDir)\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="RDTools">
        <HintPath>$(GameDir)\RDTools.dll</HintPath>
      </Reference>
    </ItemGroup>
  </Target>

  <ItemGroup>
    <!-- Data files -->
    <None Include="..\World\data\items.yml" Link="World\data\items.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\World\data\locations.yml" Link="World\data\locations.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\World\data\world.yml" Link="World\data\world.yml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <!-- Assets -->
    <None Update="World\assets\wardicons\archipelago.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
