using Archipelago.MultiClient.Net.Enums;

namespace RhythmDoctor.Archipelago.Client;

internal sealed class Client
{
  ArchipelagoSession? Session;

  Client(string server, string username, string? password = null)
  {
    CreateSession(server);
  }

  internal ArchipelagoSession CreateSession(string server)
  {
    Session = ArchipelagoSessionFactory.CreateSession(server);
    return Session;
  }

  internal LoginResult Connect(string name, string? password = null, bool deathLink = false)
  {
    if (Session == null)
    {
      throw new ArgumentNullException("Session is null");
    }

    string[] tags = new string[1];
    if (deathLink)
    {
      tags[0] = "DeathLink";
    }

    return Session.TryConnectAndLogin(
      "Rhythm Doctor",
      name,
      ItemsHandlingFlags.AllItems,
      new Version("APWorldInformation.Version"), //fixme
      tags,
      null, // Randomly generated by Archipelago.MultiClient.Net
      password,
      true
    );
  }
}
