namespace RhythmDoctor.Archipelago.World;

internal static class Bindings
{
  #region Generated by APWorld
  internal const string GAME = "Rhythm Doctor";
  internal const long SLEEVE_PAINT_ITEM_ID = 56;

  /// <summary>
  /// <see cref="Level"/> to corresponding <see cref="LevelBase"/>
  /// </summary>
  /// <seeAlso cref="RegularStage"/>
  /// <seeAlso cref="BossStage"/>
  internal static readonly Dictionary<Level, BaseStage> LevelToStage = new()
  {
    { Level.OrientalTechno, new RegularStage(Act.Act1, 1, 2, 3) },
    { Level.OrientalDubstep, new RegularStage(Act.Act1, 4, 5, 6) },
    { Level.Intimate, new RegularStage(Act.Act1, 7, 8, 9) },
    { Level.IntimateH, new RegularStage(Act.Act1, 10, 11, 12) },
    { Level.GongXi, new RegularStage(Act.Act1, 13, 14, 15) },
    { Level.Halloween, new RegularStage(Act.Act1, 16, 17, 18) },
    { Level.Garden, new RegularStage(Act.Act3, 21, 22, 23) },
    { Level.Lounge, new RegularStage(Act.Act3, 24, 25, 26) },
    { Level.Classy, new RegularStage(Act.Act3, 27, 28, 29) },
    { Level.ClassyH, new RegularStage(Act.Act3, 30, 31, 32) },
    { Level.DistantDuet, new RegularStage(Act.Act3, 33, 34, 35) },
    { Level.DistantDuetH, new RegularStage(Act.Act3, 36, 37, 38) },
    { Level.Lofi, new RegularStage(Act.Act2, 43, 44, 45) },
    { Level.CareLess, new RegularStage(Act.Act2, 46, 47, 48) },
    { Level.SVT, new RegularStage(Act.Act2, 49, 50, 51) },
    { Level.Unreachable, new RegularStage(Act.Act2, 52, 53, 54) },
    { Level.Smokin, new RegularStage(Act.Act2, 55, 56, 57) },
    { Level.Pomeranian, new RegularStage(Act.Act2, 58, 59, 60) },
    { Level.SongOfTheSea, new RegularStage(Act.Act2, null, null, 61) },
    { Level.SongOfTheSeaH, new RegularStage(Act.Act2, null, null, 62) },
    { Level.BeansHopper, new RegularStage(Act.Act2, 63, 64, 65) },
    { Level.Bitterness, new BossStage(Act.Act7, 66, 67, 68) },
    { Level.Heldbeats, new RegularStage(Act.Act4, 71, 72, 73) },
    { Level.Rollerdisco, new RegularStage(Act.Act4, 74, 75, 76) },
    { Level.Invisible, new RegularStage(Act.Act4, 77, 78, 79) },
    { Level.InvisibleH, new RegularStage(Act.Act4, 80, 81, 82) },
    { Level.Steinway, new RegularStage(Act.Act4, 83, 84, 85) },
    { Level.SteinwayH, new RegularStage(Act.Act4, 86, 87, 88) },
    { Level.KnowYou, new RegularStage(Act.Act4, 89, 90, 91) },
    { Level.Murmurs, new RegularStage(Act.Act4, 92, 93, 94) },
    { Level.LuckyBreak, new RegularStage(Act.Act5, 97, 98, 99) },
    { Level.Injury, new RegularStage(Act.Act5, 100, 101, 102) },
    { Level.Freezeshot, new RegularStage(Act.Act5, 103, 104, 105) },
    { Level.FreezeshotH, new RegularStage(Act.Act5, 106, 107, 108) },
    { Level.AthleteTherapy, new RegularStage(Act.Act5, null, null, 109) },
    { Level.StevensonsTango, new RegularStage(Act.Act5, 110, 111, 112) },
    { Level.HaileyDuet, new RegularStage(Act.Act6, 126, 127, 128) },
    { Level.EdegaRave, new RegularStage(Act.Act6, 129, 130, 131) },
    { Level.Blurred, new RegularStage(Act.Act7, 135, 136, 137) },
    { Level.VividStasis, new RegularStage(Act.None, 144, 145, 146) },
    { Level.SparkLine, new RegularStage(Act.None, 147, 148, 149) },
    { Level.Unbeatable, new RegularStage(Act.None, 150, 151, 152) },
    { Level.MeetAndTweet, new RegularStage(Act.None, 153, 154, 155) },
    { Level.BlackestLuxuryCar, new RegularStage(Act.None, 156, 157, 158) },
    { Level.TapeStopNight, new RegularStage(Act.None, 159, 160, 161) },
    { Level.The90sDecision, new RegularStage(Act.None, 162, 163, 164) },
    { Level.HelpingHands, new RegularStage(Act.None, 165, 166, 167) },
    { Level.ArtExercise, new RegularStage(Act.None, 168, 169, 170) },
    { Level.OrientalInsomniac, new BossStage(Act.Act1, 19, null, 20) },
    { Level.Boss2, new BossStage(Act.Act2, 69, null, 70) },
    { Level.InsomniacHard, new BossStage(Act.Act4, 95, null, 96) },
    { Level.AthleteFinale, new BossStage(Act.Act5, 123, 124, 125) },
    { Level.PaigesReckoning, new BossStage(Act.Act6, 132, 133, 134) },
    { Level.Montage, new BossStage(Act.Act7, 138, 139, 140) },
    { Level.Montage2, new BossStage(Act.Act7, 141, 142, 143) },
    {
      Level.Lesmis,
      new BossStage(Act.Act3, 39, null, 40, new Dictionary<string, long> { { "dog_clear", 41 }, { "dog_perfect", 42 } })
    },
  };

  /// <summary>
  /// Level ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Level> ItemIdToLevel = new()
  {
    { 1, Level.OrientalTechno },
    { 2, Level.OrientalDubstep },
    { 3, Level.Intimate },
    { 4, Level.IntimateH },
    { 5, Level.GongXi },
    { 6, Level.Halloween },
    { 7, Level.Garden },
    { 8, Level.Lounge },
    { 9, Level.Classy },
    { 10, Level.ClassyH },
    { 11, Level.DistantDuet },
    { 12, Level.DistantDuetH },
    { 13, Level.Lofi },
    { 14, Level.CareLess },
    { 15, Level.SVT },
    { 16, Level.Unreachable },
    { 17, Level.Smokin },
    { 18, Level.Pomeranian },
    { 19, Level.SongOfTheSea },
    { 20, Level.SongOfTheSeaH },
    { 21, Level.BeansHopper },
    { 22, Level.Bitterness },
    { 23, Level.Heldbeats },
    { 24, Level.Rollerdisco },
    { 25, Level.Invisible },
    { 26, Level.InvisibleH },
    { 27, Level.Steinway },
    { 28, Level.SteinwayH },
    { 29, Level.KnowYou },
    { 30, Level.Murmurs },
    { 31, Level.LuckyBreak },
    { 32, Level.Injury },
    { 33, Level.Freezeshot },
    { 34, Level.FreezeshotH },
    { 35, Level.AthleteTherapy },
    { 36, Level.StevensonsTango },
    { 37, Level.RhythmWeightlifter },
    { 38, Level.HaileyDuet },
    { 39, Level.EdegaRave },
    { 40, Level.Blurred },
    { 41, Level.VividStasis },
    { 42, Level.SparkLine },
    { 43, Level.Unbeatable },
    { 44, Level.MeetAndTweet },
    { 45, Level.BlackestLuxuryCar },
    { 46, Level.TapeStopNight },
    { 47, Level.The90sDecision },
    { 48, Level.HelpingHands },
    { 49, Level.ArtExercise },
  };

  /// <summary>
  /// Trap and powerup item ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Type> TrapItemIdToLevel = new()
  {
    { 60, typeof(FragileHeartTrapPatch) },
    { 61, typeof(HardDifficultyTrapPatch) },
    { 62, typeof(ScrambleCharactersTrapPatch) },
    { 63, typeof(ScrambleBeatsoundsTrapPatch) },
    { 64, typeof(ScrambleHitsoundsTrapPatch) },
    { 65, typeof(ChilliSpeedTrapPatch) },
    { 66, typeof(GhostTapTrapPatch) },
    { 57, typeof(StrongHeartPowerupPatch) },
    { 58, typeof(EasyDifficultyPowerupPatch) },
    { 59, typeof(IceSpeedTrapPatch) },
  };

  /// <summary>
  /// Key item ID to corresponding <see cref="Region"/>
  /// </summary>
  internal static readonly Dictionary<long, Region> KeyItemIdToWard = new()
  {
    { 50, Region.SVTWard },
    { 51, Region.Train },
    { 52, Region.PhysiotherapyWard },
    { 55, Region.RecordsRoom },
    { 53, Region.Basement },
    { 54, Region.GardenRoom },
  };

  /// <summary>
  /// Rhythm Weightlifter stage to its corresponding location ID.
  /// </summary>
  internal static readonly long[] RhythmWeightlifterStageToLocationID =
  [
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
  ];
  #endregion

  internal static readonly IReadOnlyCollection<Type> Traps = TrapItemIdToLevel.Values;

  internal static readonly IReadOnlyCollection<Level> Levels = LevelToStage.Keys;

  internal static readonly Dictionary<Level, Act> LevelToAct = LevelToStage.ToDictionary(
    pair => pair.Key,
    pair => pair.Value.StageAct
  );

  internal static readonly Dictionary<Act, IEnumerable<Level>> LevelsInAct = LevelToStage
    .GroupBy(pair => pair.Value.StageAct)
    .ToDictionary(grouping => grouping.Key, grouping => grouping.Select(c => c.Key));

  internal static readonly Level[] LevelsThatDoNotUnlockBoss = [Level.RhythmWeightlifter];

  internal static readonly Dictionary<Act, Level[]> ActBoss = new()
  {
    { Act.Act1, [Level.OrientalInsomniac] },
    { Act.Act2, [Level.Boss2] },
    { Act.Act3, [Level.Lesmis] },
    { Act.Act4, [Level.InsomniacHard] },
    { Act.Act5, [Level.AthleteFinale] },
    { Act.Act6, [Level.PaigesReckoning] },
    { Act.Act7, [Level.Montage, Level.Montage2] },
  };
}
