namespace RhythmDoctor.Archipelago.World;

internal static class Bindings
{
  #region Generated by APWorld
  internal const string GAME = "Rhythm Doctor";
  internal const long SLEEVE_PAINT_ITEM_ID = 49;

  /// <summary>
  /// <see cref="Level"/> to corresponding <see cref="LevelBase"/>
  /// </summary>
  /// <seeAlso cref="RegularStage"/>
  /// <seeAlso cref="BossStage"/>
  internal static readonly Dictionary<Level, BaseStage> LevelToStage =
    new()
    {
      { Level.OrientalTechno, new RegularStage(Act.Act1, 1, 2, 3) },
      { Level.OrientalDubstep, new RegularStage(Act.Act1, 4, 5, 6) },
      { Level.Intimate, new RegularStage(Act.Act1, 7, 8, 9) },
      { Level.IntimateH, new RegularStage(Act.Act1, 10, 11, 12) },
      { Level.GongXi, new RegularStage(Act.Act1, 13, 14, 15) },
      { Level.Halloween, new RegularStage(Act.Act1, 16, 17, 18) },
      { Level.Garden, new RegularStage(Act.Act3, 21, 22, 23) },
      { Level.Lounge, new RegularStage(Act.Act3, 24, 25, 26) },
      { Level.Classy, new RegularStage(Act.Act3, 27, 28, 29) },
      { Level.ClassyH, new RegularStage(Act.Act3, 30, 31, 32) },
      { Level.DistantDuet, new RegularStage(Act.Act3, 33, 34, 35) },
      { Level.DistantDuetH, new RegularStage(Act.Act3, 36, 37, 38) },
      { Level.Lofi, new RegularStage(Act.Act2, 43, 44, 45) },
      { Level.CareLess, new RegularStage(Act.Act2, 46, 47, 48) },
      { Level.SVT, new RegularStage(Act.Act2, 49, 50, 51) },
      { Level.Unreachable, new RegularStage(Act.Act2, 52, 53, 54) },
      { Level.Smokin, new RegularStage(Act.Act2, 55, 56, 57) },
      { Level.Pomeranian, new RegularStage(Act.Act2, 58, 59, 60) },
      { Level.SongOfTheSea, new RegularStage(Act.Act2, null, null, 61) },
      { Level.SongOfTheSeaH, new RegularStage(Act.Act2, null, null, 62) },
      { Level.BeansHopper, new RegularStage(Act.Act2, 63, 64, 65) },
      { Level.Heldbeats, new RegularStage(Act.Act4, 68, 69, 70) },
      { Level.Rollerdisco, new RegularStage(Act.Act4, 71, 72, 73) },
      { Level.Invisible, new RegularStage(Act.Act4, 74, 75, 76) },
      { Level.InvisibleH, new RegularStage(Act.Act4, 77, 78, 79) },
      { Level.Steinway, new RegularStage(Act.Act4, 80, 81, 82) },
      { Level.SteinwayH, new RegularStage(Act.Act4, 83, 84, 85) },
      { Level.KnowYou, new RegularStage(Act.Act4, 86, 87, 88) },
      { Level.Murmurs, new RegularStage(Act.Act4, 89, 90, 91) },
      { Level.LuckyBreak, new RegularStage(Act.Act5, 94, 95, 96) },
      { Level.Injury, new RegularStage(Act.Act5, 97, 98, 99) },
      { Level.Freezeshot, new RegularStage(Act.Act5, 100, 101, 102) },
      { Level.FreezeshotH, new RegularStage(Act.Act5, 103, 104, 105) },
      { Level.AthleteTherapy, new RegularStage(Act.Act5, null, null, 106) },
      { Level.VividStasis, new RegularStage(Act.None, 120, 121, 122) },
      { Level.SparkLine, new RegularStage(Act.None, 123, 124, 125) },
      { Level.Unbeatable, new RegularStage(Act.None, 126, 127, 128) },
      { Level.MeetAndTweet, new RegularStage(Act.None, 129, 130, 131) },
      { Level.BlackestLuxuryCar, new RegularStage(Act.None, 132, 133, 134) },
      { Level.TapeStopNight, new RegularStage(Act.None, 135, 136, 137) },
      { Level.The90sDecision, new RegularStage(Act.None, 138, 139, 140) },
      { Level.HelpingHands, new RegularStage(Act.None, 141, 142, 143) },
      { Level.ArtExercise, new RegularStage(Act.None, 144, 145, 146) },
      { Level.OrientalInsomniac, new BossStage(Act.Act1, 19, null, 20) },
      { Level.Boss2, new BossStage(Act.Act2, 66, null, 67) },
      { Level.InsomniacHard, new BossStage(Act.Act4, 92, null, 93) },
      { Level.AthleteFinale, new BossStage(Act.Act5, 117, 118, 119) },
      {
        Level.Lesmis,
        new BossStage(
          Act.Act3,
          39,
          null,
          40,
          new Dictionary<string, long> { { "dog_clear", 41 }, { "dog_perfect", 42 } }
        )
      },
    };

  /// <summary>
  /// Level ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Level> ItemIdToLevel =
    new()
    {
      { 1, Level.OrientalTechno },
      { 2, Level.OrientalDubstep },
      { 3, Level.Intimate },
      { 4, Level.IntimateH },
      { 5, Level.GongXi },
      { 6, Level.Halloween },
      { 7, Level.Garden },
      { 8, Level.Lounge },
      { 9, Level.Classy },
      { 10, Level.ClassyH },
      { 11, Level.DistantDuet },
      { 12, Level.DistantDuetH },
      { 13, Level.Lofi },
      { 14, Level.CareLess },
      { 15, Level.SVT },
      { 16, Level.Unreachable },
      { 17, Level.Smokin },
      { 18, Level.Pomeranian },
      { 19, Level.SongOfTheSea },
      { 20, Level.SongOfTheSeaH },
      { 21, Level.BeansHopper },
      { 22, Level.Heldbeats },
      { 23, Level.Rollerdisco },
      { 24, Level.Invisible },
      { 25, Level.InvisibleH },
      { 26, Level.Steinway },
      { 27, Level.SteinwayH },
      { 28, Level.KnowYou },
      { 29, Level.Murmurs },
      { 30, Level.LuckyBreak },
      { 31, Level.Injury },
      { 32, Level.Freezeshot },
      { 33, Level.FreezeshotH },
      { 34, Level.AthleteTherapy },
      { 44, Level.RhythmWeightlifter },
      { 35, Level.VividStasis },
      { 36, Level.SparkLine },
      { 37, Level.Unbeatable },
      { 38, Level.MeetAndTweet },
      { 39, Level.BlackestLuxuryCar },
      { 40, Level.TapeStopNight },
      { 41, Level.The90sDecision },
      { 42, Level.HelpingHands },
      { 43, Level.ArtExercise },
    };

  /// <summary>
  /// Trap and powerup item ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Type> TrapItemIdToLevel =
    new()
    {
      { 53, typeof(FragileHeartTrapPatch) },
      { 54, typeof(HardDifficultyTrapPatch) },
      { 55, typeof(ScrambleCharactersTrapPatch) },
      { 56, typeof(ScrambleBeatsoundsTrapPatch) },
      { 57, typeof(ScrambleHitsoundsTrapPatch) },
      { 58, typeof(ChilliSpeedTrapPatch) },
      { 59, typeof(GhostTapTrapPatch) },
      { 50, typeof(StrongHeartPowerupPatch) },
      { 51, typeof(EasyDifficultyPowerupPatch) },
      { 52, typeof(IceSpeedTrapPatch) },
    };

  /// <summary>
  /// Key item ID to corresponding <see cref="Region"/>
  /// </summary>
  internal static readonly Dictionary<long, Region> KeyItemIdToWard =
    new()
    {
      { 44, Region.SVTWard },
      { 45, Region.Train },
      { 46, Region.PhysiotherapyWard },
      { 47, Region.Basement },
      { 48, Region.ArtRoom },
    };

  /// <summary>
  /// Rhythm Weightlifter stage to its corresponding location ID.
  /// </summary>
  internal static readonly long[] RhythmWeightlifterStageToLocationID =
  [
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
  ];
  #endregion

  internal static readonly IReadOnlyCollection<Type> Traps = TrapItemIdToLevel.Values;

  internal static readonly IReadOnlyCollection<Level> Levels = LevelToStage.Keys;

  internal static readonly Dictionary<Level, Act> LevelToAct = LevelToStage.ToDictionary(
    pair => pair.Key,
    pair => pair.Value.StageAct
  );

  internal static readonly Dictionary<Act, IEnumerable<Level>> LevelsInAct = LevelToStage
    .GroupBy(pair => pair.Value.StageAct)
    .ToDictionary(grouping => grouping.Key, grouping => grouping.Select(c => c.Key));

  internal static readonly Dictionary<Act, int> LevelCountInActUnlockingBoss =
    new()
    {
      { Act.Act1, 4 },
      { Act.Act2, 8 },
      { Act.Act3, 6 },
      { Act.Act4, 8 },
      { Act.Act5, 5 },
    };

  internal static readonly Level[] LevelsThatDoNotUnlockBoss = [Level.RhythmWeightlifter];

  internal static readonly Dictionary<Act, Level> ActBoss =
    new()
    {
      { Act.Act1, Level.OrientalInsomniac },
      { Act.Act2, Level.Boss2 },
      { Act.Act3, Level.Lesmis },
      { Act.Act4, Level.InsomniacHard },
      { Act.Act5, Level.AthleteFinale },
    };
}
