namespace RhythmDoctor.Archipelago.World;

internal static class Bindings
{
  #region Generated by APWorld
  internal const string GAME = "Rhythm Doctor";
  internal const long SLEEVE_PAINT_ITEM_ID = 56;

  /// <summary>
  /// <see cref="Level"/> to corresponding <see cref="LevelBase"/>
  /// </summary>
  /// <seeAlso cref="RegularStage"/>
  /// <seeAlso cref="BossStage"/>
  internal static readonly Dictionary<Level, BaseStage> LevelToStage =
    new()
    {
      { Level.OrientalTechno, new RegularStage(Act.Act1, 1, 2, 3) },
      { Level.OrientalDubstep, new RegularStage(Act.Act1, 4, 5, 6) },
      { Level.Intimate, new RegularStage(Act.Act1, 7, 8, 9) },
      { Level.IntimateH, new RegularStage(Act.Act1, 10, 11, 12) },
      { Level.GongXi, new RegularStage(Act.Act1, 13, 14, 15) },
      { Level.Halloween, new RegularStage(Act.Act1, 16, 17, 18) },
      { Level.Garden, new RegularStage(Act.Act3, 19, 20, 21) },
      { Level.Lounge, new RegularStage(Act.Act3, 22, 23, 24) },
      { Level.Classy, new RegularStage(Act.Act3, 25, 26, 27) },
      { Level.ClassyH, new RegularStage(Act.Act3, 28, 29, 30) },
      { Level.DistantDuet, new RegularStage(Act.Act3, 31, 32, 33) },
      { Level.DistantDuetH, new RegularStage(Act.Act3, 34, 35, 36) },
      { Level.Lofi, new RegularStage(Act.Act2, 37, 38, 39) },
      { Level.CareLess, new RegularStage(Act.Act2, 40, 41, 42) },
      { Level.SVT, new RegularStage(Act.Act2, 43, 44, 45) },
      { Level.Unreachable, new RegularStage(Act.Act2, 46, 47, 48) },
      { Level.Smokin, new RegularStage(Act.Act2, 49, 50, 51) },
      { Level.Pomeranian, new RegularStage(Act.Act2, 52, 53, 54) },
      { Level.SongOfTheSea, new RegularStage(Act.Act2, null, null, 55) },
      { Level.SongOfTheSeaH, new RegularStage(Act.Act2, null, null, 56) },
      { Level.BeansHopper, new RegularStage(Act.Act2, 57, 58, 59) },
      { Level.Heldbeats, new RegularStage(Act.Act4, 60, 61, 62) },
      { Level.Rollerdisco, new RegularStage(Act.Act4, 63, 64, 65) },
      { Level.Invisible, new RegularStage(Act.Act4, 66, 67, 68) },
      { Level.InvisibleH, new RegularStage(Act.Act4, 69, 70, 71) },
      { Level.Steinway, new RegularStage(Act.Act4, 72, 73, 74) },
      { Level.SteinwayH, new RegularStage(Act.Act4, 75, 76, 77) },
      { Level.KnowYou, new RegularStage(Act.Act4, 78, 79, 80) },
      { Level.Murmurs, new RegularStage(Act.Act4, 81, 82, 83) },
      { Level.LuckyBreak, new RegularStage(Act.Act5, 84, 85, 86) },
      { Level.Injury, new RegularStage(Act.Act5, 87, 88, 89) },
      { Level.Freezeshot, new RegularStage(Act.Act5, 90, 91, 92) },
      { Level.FreezeshotH, new RegularStage(Act.Act5, 93, 94, 95) },
      { Level.AthleteTherapy, new RegularStage(Act.Act5, null, null, 96) },
      { Level.VividStasis, new RegularStage(Act.None, 107, 108, 109) },
      { Level.SparkLine, new RegularStage(Act.None, 110, 111, 112) },
      { Level.Unbeatable, new RegularStage(Act.None, 113, 114, 115) },
      { Level.MeetAndTweet, new RegularStage(Act.None, 116, 117, 118) },
      { Level.BlackestLuxuryCar, new RegularStage(Act.None, 119, 120, 121) },
      { Level.TapeStopNight, new RegularStage(Act.None, 122, 123, 124) },
      { Level.The90sDecision, new RegularStage(Act.None, 125, 126, 127) },
      { Level.HelpingHands, new RegularStage(Act.None, 128, 129, 130) },
      { Level.ArtExercise, new RegularStage(Act.None, 131, 132, 133) },
      { Level.OrientalInsomniac, new BossStage(Act.Act1, 134, null, 135) },
      { Level.Boss2, new BossStage(Act.Act2, 136, null, 137) },
      { Level.InsomniacHard, new BossStage(Act.Act4, 142, null, 143) },
      { Level.AthleteFinale, new BossStage(Act.Act5, 144, 145, 146) },
      {
        Level.Lesmis,
        new BossStage(
          Act.Act3,
          138,
          null,
          139,
          new Dictionary<string, long> { { "dog_clear", 140 }, { "dog_perfect", 141 } }
        )
      },
    };

  /// <summary>
  /// Level ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Level> ItemIdToLevel =
    new()
    {
      { 1, Level.OrientalTechno },
      { 2, Level.OrientalDubstep },
      { 3, Level.Intimate },
      { 4, Level.IntimateH },
      { 5, Level.GongXi },
      { 6, Level.Halloween },
      { 7, Level.Garden },
      { 8, Level.Lounge },
      { 9, Level.Classy },
      { 10, Level.ClassyH },
      { 11, Level.DistantDuet },
      { 12, Level.DistantDuetH },
      { 13, Level.Lofi },
      { 14, Level.CareLess },
      { 15, Level.SVT },
      { 16, Level.Unreachable },
      { 17, Level.Smokin },
      { 18, Level.Pomeranian },
      { 19, Level.SongOfTheSea },
      { 20, Level.SongOfTheSeaH },
      { 21, Level.BeansHopper },
      { 22, Level.Heldbeats },
      { 23, Level.Rollerdisco },
      { 24, Level.Invisible },
      { 25, Level.InvisibleH },
      { 26, Level.Steinway },
      { 27, Level.SteinwayH },
      { 28, Level.KnowYou },
      { 29, Level.Murmurs },
      { 30, Level.LuckyBreak },
      { 31, Level.Injury },
      { 32, Level.Freezeshot },
      { 33, Level.FreezeshotH },
      { 34, Level.AthleteTherapy },
      { 35, Level.RhythmWeightlifter },
      { 36, Level.VividStasis },
      { 37, Level.SparkLine },
      { 38, Level.Unbeatable },
      { 39, Level.MeetAndTweet },
      { 40, Level.BlackestLuxuryCar },
      { 41, Level.TapeStopNight },
      { 42, Level.The90sDecision },
      { 43, Level.HelpingHands },
      { 44, Level.ArtExercise },
    };

  /// <summary>
  /// Trap item ID to corresponding <see cref="Level"/>
  /// </summary>
  internal static readonly Dictionary<long, Type> TrapItemIdToLevel =
    new()
    {
      { 60, typeof(FragileHeartTrapPatch) },
      { 61, typeof(HardDifficultyTrapPatch) },
      { 62, typeof(ScrambleCharactersTrapPatch) },
      { 63, typeof(ScrambleBeatsoundsTrapPatch) },
      { 64, typeof(ScrambleHitsoundsTrapPatch) },
      { 65, typeof(ChilliSpeedTrapPatch) },
      { 66, typeof(GhostTapTrapPatch) },
      { 57, typeof(StrongHeartPowerupPatch) },
      { 58, typeof(EasyDifficultyPowerupPatch) },
      { 59, typeof(IceSpeedTrapPatch) },
    };

  /// <summary>
  /// Key item ID to corresponding <see cref="Region"/>
  /// </summary>
  internal static readonly Dictionary<long, Region> KeyItemIdToWard =
    new()
    {
      { 51, Region.SVTWard },
      { 52, Region.Train },
      { 53, Region.PhysiotherapyWard },
      { 54, Region.Basement },
      { 55, Region.ArtRoom },
    };

  /// <summary>
  /// Rhythm Weightlifter stage to its corresponding location ID.
  /// </summary>
  internal static readonly long[] RhythmWeightlifterStageToLocationID = [97, 98, 99, 100, 101, 102, 103, 104, 105, 106];
  #endregion

  internal static readonly IReadOnlyCollection<Level> Levels = LevelToStage.Keys;

  internal static readonly Dictionary<Level, Act> LevelToAct = LevelToStage.ToDictionary(
    pair => pair.Key,
    pair => pair.Value.StageAct
  );

  internal static readonly Dictionary<Act, IEnumerable<Level>> LevelsInAct = LevelToStage
    .GroupBy(pair => pair.Value.StageAct)
    .ToDictionary(grouping => grouping.Key, grouping => grouping.Select(c => c.Key));

  internal static readonly Dictionary<Act, int> ClearedLevelsToUnlockBoss =
    new()
    {
      { Act.Act1, 2 },
      { Act.Act2, 4 },
      { Act.Act3, 3 },
      { Act.Act4, 4 },
      { Act.Act5, 3 },
    };

  internal static readonly Dictionary<Act, Level> ActBoss =
    new()
    {
      { Act.Act1, Level.OrientalInsomniac },
      { Act.Act2, Level.Boss2 },
      { Act.Act3, Level.Lesmis },
      { Act.Act4, Level.InsomniacHard },
      { Act.Act5, Level.AthleteFinale },
    };
}
