name: Debug Build
on:
  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/main.yml"
      - "!RhythmDoctor.Archipelago.sln"
      - "!RhythmDoctor.Archipelago/**"
      - "RhythmDoctor.Archipelago/.idea"
      - "RhythmDoctor.Archipelago/.editorconfig"

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v5.0.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget

      - name: Build client
        run: dotnet publish RhythmDoctor.Archipelago --configuration Debug --output build --verbosity normal

      - name: Upload client plugin
        uses: actions/upload-artifact@v7.0.1
        with:
          name: "RhythmDoctor.Archipelago"
          path: |
            build/Assets
            build/Archipelago.MultiClient.Net.dll
            build/io.github.nonperforming.pulse.dll
            build/io.github.nonperforming.pulse.pdb
            build/RhythmDoctor.Archipelago.dll
            build/RhythmDoctor.Archipelago.pdb
          if-no-files-found: error
