name: Build
on:
  pull_request:
    paths-ignore:
      - "**LICENSE"
      - "**.editorconfig"
      - "**.git**"
      - "!.github/workflows/**"
  push:
    paths-ignore:
      - "**LICENSE"
      - "**.editorconfig"
      - "**.git**"
      - "!.github/workflows/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0

      - name: Build client
        run: dotnet build --configuration Debug

      - name: Upload client plugin
        uses: actions/upload-artifact@v4.4.3
        with:
          name: "RhythmDoctor.Archipelago.dll"
          path: |
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/World/data/items.yml"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/World/data/locations.yml"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/World/data/options.yml"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/World/data/world.yml"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/Archipelago.MultiClient.Net.dll"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/RhythmDoctor.Archipelago.dll"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/RhythmDoctor.Archipelago.pdb"
            "RhythmDoctor.Archipelago/bin/Debug/netstandard2.1/YamlDotNet.dll"
          if-no-files-found: error

      - name: Upload APWorld
        uses: actions/upload-artifact@v4.4.3
        with:
          name: "RhythmDoctor.apworld"
          path: "World/"
          if-no-files-found: error


